name: Preprocessing Workflow

on:
  push:
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Versi terbaru dari checkout action

    - name: Set up Python 3.8
      uses: actions/setup-python@v4  # Versi terbaru dari setup-python action
      with:
        python-version: '3.8'

    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Nama-siswa.py
